#!/usr/bin/env python3
"""make_example_data.py -- generate SYNTHETIC example CSVs.

READ THIS FIRST
===============
Everything this script writes is FABRICATED. It exists so that `make all` runs
end to end on a laptop with no Kubernetes cluster, exercising every loader,
every fit, every test and every figure. It is a pipeline test, not data.

Nothing here was measured. The numbers come from closed-form queueing formulas
with round, obviously-chosen constants and a fixed random seed. They are
deliberately smooth and deliberately reproducible, which is exactly what real
measurements are not.

Three independent guards keep this output out of a paper:

  1. Every file begins with a comment line containing "SYNTHETIC EXAMPLE DATA",
     which analysis/io.py detects.
  2. The output directory is named `example`, which the same guard also detects.
  3. Figures rendered from it carry a diagonal watermark, and generated LaTeX
     macros are wrapped in \\SYNTHVAL so they typeset in red with a dagger.

The controller trace is not fabricated by this script beyond its inputs: the
observation columns are generated here, and the decision, mode and
actuation_latency_ms columns are produced by running the REAL controller over
them in --dry-run --replay. That keeps one implementation of the policy in the
repository rather than two that can disagree.

Usage:  python data/make_example_data.py [--out data/example] [--seed 20250906]
"""
from __future__ import annotations

import argparse
import csv
import math
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np

ARTIFACT_ROOT = Path(__file__).resolve().parent.parent

BANNER = (
    "# SYNTHETIC EXAMPLE DATA - NOT FOR PUBLICATION. Generated by "
    "data/make_example_data.py from closed-form queueing formulas with a fixed "
    "seed. Nothing in this file was measured.\n"
)

# --- synthetic scenario constants -------------------------------------------
# Round numbers, chosen by hand to give the pipeline something with the right
# shape: monotone cost as security layers are added, an elbow inside the ramp,
# S7 (sidecar offload) cheaper on the application than S5, S9 (cluster) faster
# but no cheaper per request. They are illustrative, not representative.
SCENARIOS = {
    #        mu (rps)  network offset (ms)  verify cost carried by
    "S1": dict(mu=1000.0, offset=2.00, verify_in="none"),
    "S2": dict(mu=900.0,  offset=2.40, verify_in="none"),
    "S3": dict(mu=800.0,  offset=2.80, verify_in="none"),
    "S4": dict(mu=700.0,  offset=2.20, verify_in="app"),
    "S5": dict(mu=600.0,  offset=2.90, verify_in="app"),
    "S6": dict(mu=380.0,  offset=2.90, verify_in="app"),
    "S7": dict(mu=780.0,  offset=3.20, verify_in="sidecar"),
    "S8": dict(mu=820.0,  offset=2.90, verify_in="app"),
    "S9": dict(mu=1900.0, offset=2.90, verify_in="app"),
}

RAMP_SCENARIOS = ["S1", "S3", "S5"]
DENSITY_SCENARIOS = ["S1", "S5", "S6", "S7"]
ENVIRONMENT = "local"
N_RUNS = 3
N_RAMP_SWEEPS = 3
CPU_LIMIT_MILLICORES = 1000.0
VUS = 100
THINK_S = 1.0
WARMUP_S, STEADY_S, RAMPDOWN_S = 20.0, 60.0, 10.0


def md1_ms(lam: float, mu: float, offset_ms: float) -> float:
    """M/D/1 mean response time in ms, plus a constant network offset."""
    rho = lam / mu
    if rho >= 1.0:
        return math.inf
    return 1000.0 * (1.0 / mu + rho / (2.0 * mu * (1.0 - rho))) + offset_ms


def cpu_millicores(lam: float, mu: float, verify_in: str, component: str) -> float:
    """Synthetic CPU: service time times rate, plus a fixed idle floor.

    The verification cost is carried by whichever component the scenario says
    carries it, which is the whole point of the S5/S7 comparison.
    """
    service_ms = 1000.0 / mu
    verify_ms = 0.35 if verify_in != "none" else 0.0
    if component == "app":
        base = service_ms - (verify_ms if verify_in == "sidecar" else 0.0)
        return 40.0 + lam * max(base, 0.05)
    if component == "sidecar":
        base = 0.55 + (verify_ms if verify_in == "sidecar" else 0.0)
        return 20.0 + lam * base
    return 15.0 + lam * 0.40  # ingress


def write_csv(path: Path, header: list[str], rows: list[list]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as fh:
        fh.write(BANNER)
        writer = csv.writer(fh)
        writer.writerow(header)
        writer.writerows(rows)
    print(f"  {path}  ({len(rows)} rows)")


def fmt(value: float, digits: int = 4) -> str:
    return "" if value is None or not math.isfinite(value) else f"{value:.{digits}f}"


# ---------------------------------------------------------------------------
# scenarios.csv + latency_samples.csv
# ---------------------------------------------------------------------------

def make_scenarios(rng, out_dir: Path):
    header = [
        "scenario", "environment", "run", "throughput_rps", "throughput_window",
        "latency_mean_ms", "latency_p50_ms", "latency_p90_ms", "latency_p95_ms",
        "latency_p99_ms", "latency_stdev_ms", "cpu_app_millicores",
        "cpu_sidecar_millicores", "cpu_ingress_millicores", "cpu_limit_millicores",
    ]
    rows, sample_rows = [], []

    for scenario, spec in SCENARIOS.items():
        mu, offset = spec["mu"], spec["offset"]
        for run in range(1, N_RUNS + 1):
            # Closed loop: VUs / (think + latency) is the fixed point. Two
            # iterations is plenty at these latencies.
            latency_s = 0.005
            for _ in range(6):
                lam = VUS / (THINK_S + latency_s)
                latency_s = md1_ms(lam, mu, offset) / 1000.0
            steady_rps = VUS / (THINK_S + latency_s)
            mean_ms = latency_s * 1000.0

            # Between-run variation: a few percent, which is what makes the
            # run-means family in stats_tests.py have anything to test.
            run_factor = 1.0 + rng.normal(0.0, 0.03)
            mean_ms *= run_factor

            # Per-request samples: lognormal with the target mean. Latency is
            # right-skewed, which is the reason stats_tests.py bothers with
            # Mann-Whitney and a median-difference interval.
            sigma = 0.35
            n_samples = 2000
            draws = rng.lognormal(mean=math.log(mean_ms) - sigma ** 2 / 2,
                                  sigma=sigma, size=n_samples)

            windows = {
                "steady": (steady_rps, draws),
                # The full profile includes ramps, so throughput over the whole
                # window is lower. This is the ambiguity amortized_cpu.py exists
                # to expose.
                "full": (steady_rps * STEADY_S / (WARMUP_S + STEADY_S + RAMPDOWN_S)
                         * 1.15, draws),
            }
            for window, (rps, values) in windows.items():
                rows.append([
                    scenario, ENVIRONMENT, run, fmt(rps, 3), window,
                    fmt(float(np.mean(values))), fmt(float(np.percentile(values, 50))),
                    fmt(float(np.percentile(values, 90))), fmt(float(np.percentile(values, 95))),
                    fmt(float(np.percentile(values, 99))), fmt(float(np.std(values, ddof=1))),
                    fmt(cpu_millicores(rps, mu, spec["verify_in"], "app"), 3),
                    fmt(cpu_millicores(rps, mu, spec["verify_in"], "sidecar"), 3),
                    fmt(cpu_millicores(rps, mu, spec["verify_in"], "ingress"), 3),
                    fmt(CPU_LIMIT_MILLICORES, 1),
                ])

            if scenario in DENSITY_SCENARIOS:
                for value in draws:
                    sample_rows.append([scenario, ENVIRONMENT, run, fmt(float(value))])

    write_csv(out_dir / "scenarios.csv", header, rows)
    write_csv(out_dir / "latency_samples.csv",
              ["scenario", "environment", "run", "latency_ms"], sample_rows)


# ---------------------------------------------------------------------------
# openloop_ramp.csv
# ---------------------------------------------------------------------------

def make_ramp(rng, out_dir: Path, max_rps: int = 400, step_rps: int = 20):
    header = ["scenario", "environment", "target_rps", "achieved_rps",
              "latency_mean_ms", "latency_p99_ms", "cpu_app_millicores",
              "cpu_sidecar_millicores", "eventloop_lag_p99_ms"]
    rows = []
    for scenario in RAMP_SCENARIOS:
        spec = SCENARIOS[scenario]
        mu, offset = spec["mu"], spec["offset"]
        for _sweep in range(N_RAMP_SWEEPS):
            for target in range(step_rps, max_rps + 1, step_rps):
                # Past ~98% utilisation the generator cannot keep up; achieved
                # falls below target, and elbow_fit.py excludes those steps.
                achieved = min(target, mu * 0.98) * (1.0 + rng.normal(0.0, 0.004))
                mean_ms = md1_ms(achieved, mu, offset) * (1.0 + rng.normal(0.0, 0.02))
                if not math.isfinite(mean_ms):
                    continue
                rho = achieved / mu
                rows.append([
                    scenario, ENVIRONMENT, target, fmt(achieved, 3),
                    fmt(mean_ms), fmt(mean_ms * (2.2 + 3.0 * rho)),
                    fmt(cpu_millicores(achieved, mu, spec["verify_in"], "app"), 3),
                    fmt(cpu_millicores(achieved, mu, spec["verify_in"], "sidecar"), 3),
                    # Event-loop lag grows sharply with utilisation: the M/D/1
                    # waiting term is the natural shape to borrow.
                    fmt(0.20 + 1000.0 * rho / (2.0 * mu * max(1e-6, 1.0 - rho))),
                ])
    write_csv(out_dir / "openloop_ramp.csv", header, rows)


# ---------------------------------------------------------------------------
# controller_trace.csv
# ---------------------------------------------------------------------------

def _controller_observation_rows(rng, mu_app, mu_side, offset, poll_s, duration_s,
                                 sidecar_windows):
    """Observation columns for the synthetic controller run.

    `sidecar_windows` is a list of (start_s, end_s) during which verification is
    assumed to be running in the sidecar, which raises the effective service rate
    from mu_app to mu_side. That is what makes latency flatten after an offload.
    """
    rows = []
    t0 = 1_757_000_000.0  # a fixed, obviously round epoch: this is not a real run
    n = int(duration_s / poll_s)
    for i in range(n):
        t_rel = i * poll_s
        fraction = t_rel / duration_s
        # Trapezoid: up for 40% of the run, hold for 20%, down for 40%.
        if fraction < 0.4:
            lam = 20.0 + (460.0 - 20.0) * (fraction / 0.4)
        elif fraction < 0.6:
            lam = 460.0
        else:
            lam = 460.0 - (460.0 - 20.0) * ((fraction - 0.6) / 0.4)
        # Noise large enough that the hysteresis has something to suppress.
        lam = max(1.0, lam * (1.0 + rng.normal(0.0, 0.035)))

        in_sidecar = any(a <= t_rel < b for a, b in sidecar_windows)
        mu = mu_side if in_sidecar else mu_app
        rho = min(0.999, lam / mu)
        rows.append([
            fmt(t0 + t_rel, 3), fmt(t_rel, 3), fmt(lam, 3),
            fmt(0.20 + 1000.0 * rho / (2.0 * mu * max(1e-6, 1.0 - rho))),
            fmt(mu, 3), fmt(rho, 4), fmt(md1_ms(lam, mu, offset)),
            "app", "hold", "", "synthetic-observation",
        ])
    return rows


def _run_controller(seed_path: Path, trace_path: Path):
    command = [
        sys.executable, str(ARTIFACT_ROOT / "controller" / "psao_controller.py"),
        "--config", str(ARTIFACT_ROOT / "controller" / "config.yaml"),
        "--dry-run", "--replay", str(seed_path), "--replay-speed", "0",
        "--out", str(trace_path), "--log-level", "WARNING",
    ]
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    if completed.returncode != 0 or not trace_path.exists():
        sys.stderr.write(completed.stdout + completed.stderr)
        raise SystemExit(
            "the controller failed on the synthetic observations, so no example "
            "controller_trace.csv was written. Fix the controller rather than "
            "hand-writing a trace."
        )
    return command


def _sidecar_windows(trace_path: Path, duration_s: float):
    """Read back the intervals the controller spent in sidecar mode."""
    with trace_path.open(newline="") as fh:
        rows = list(csv.DictReader(line for line in fh if not line.startswith("#")))
    windows, start = [], None
    for row in rows:
        t_rel = float(row["t_rel_s"])
        if row["mode"] == "sidecar" and start is None:
            start = t_rel
        elif row["mode"] != "sidecar" and start is not None:
            windows.append((start, t_rel))
            start = None
    if start is not None:
        windows.append((start, duration_s))
    return windows


def make_controller_trace(rng, out_dir: Path, poll_s: float = 2.0,
                          duration_s: float = 1800.0, max_passes: int = 4):
    """Generate the observation columns, then run the REAL controller over them.

    The load profile rises past the trigger, holds, and falls back through the
    revert band, so the resulting trace contains an offload, a revert, and the
    suppressed flaps the hysteresis produced along the way.

    TWO-WAY COUPLING, RESOLVED BY ITERATION
    ---------------------------------------
    Offloading verification to the sidecar raises the application's effective
    service rate, which lowers latency, which changes what the controller
    observes next. A single forward pass cannot represent that: the observations
    would still be on the pre-offload service curve after the offload, and the
    example figure would show no post-offload flattening at all.

    So we iterate to a fixed point. Pass 1 assumes no offload; the controller
    tells us when it offloaded; pass 2 regenerates the observations with the
    higher service rate inside that window; repeat until the windows stop moving
    (usually two passes). The result is a self-consistent SYNTHETIC scenario, not
    a simulation anybody should cite -- it exists so the figure has the shape a
    real run would have.
    """
    app_spec = SCENARIOS["S5"]         # verification on the event loop
    sidecar_spec = SCENARIOS["S7"]     # verification in the Envoy sidecar
    mu_app, offset = app_spec["mu"], app_spec["offset"]
    mu_side = sidecar_spec["mu"]

    seed_path = out_dir / ".controller_observations.synthetic.csv"
    trace_path = out_dir / "controller_trace.csv"
    header = ["t_unix", "t_rel_s", "lambda_rps", "eventloop_lag_p99_ms", "mu_eff_rps",
              "rho", "latency_mean_ms", "mode", "decision", "actuation_latency_ms",
              "trigger_reason"]

    windows = []
    command = None
    for attempt in range(max_passes):
        # Same seed each pass so the load profile itself does not move between
        # passes; only the service rate inside the offload windows changes.
        pass_rng = np.random.default_rng(20250906 + 991)
        rows = _controller_observation_rows(pass_rng, mu_app, mu_side, offset,
                                            poll_s, duration_s, windows)
        seed_path.parent.mkdir(parents=True, exist_ok=True)
        with seed_path.open("w", newline="") as fh:
            fh.write(BANNER)
            writer = csv.writer(fh)
            writer.writerow(header)
            writer.writerows(rows)

        command = _run_controller(seed_path, trace_path)
        new_windows = _sidecar_windows(trace_path, duration_s)
        print(f"  pass {attempt + 1}: sidecar windows = "
              + (", ".join(f"{a:.0f}-{b:.0f}s" for a, b in new_windows) or "none"))
        if new_windows == windows:
            break
        windows = new_windows

    print("  produced by the real controller:")
    print("    " + " ".join(command[1:]))

    # Prepend the synthetic banner: the controller writes a plain CSV, and every
    # file in data/example must declare itself.
    body = trace_path.read_text()
    trace_path.write_text(BANNER + body)
    seed_path.unlink()
    print(f"  {trace_path}  ({body.count(chr(10)) - 1} rows)")


# ---------------------------------------------------------------------------
# microbench.csv
# ---------------------------------------------------------------------------

def make_microbench(rng, out_dir: Path):
    """Synthetic stage timings with the right ORDERING and rough magnitudes.

    Run `make microbench` for real numbers; this only lets the figure render.
    """
    header = ["algorithm", "stage", "payload_kb", "iterations",
              "mean_us", "p50_us", "p99_us"]
    # Round hand-picked base costs in microseconds.
    base = {
        ("HS256", "primitive_raw"): 1.2,
        ("HS256", "primitive_preparsed"): 1.6,
        ("HS256", "decode_only"): 3.0,
        ("HS256", "full_verify"): 6.4,
        ("RS256", "primitive_raw"): 28.0,
        ("RS256", "primitive_preparsed"): 30.0,
        ("RS256", "decode_only"): 3.0,
        ("RS256", "full_verify"): 40.0,
    }
    payload_scaling = {0.5: 1.00, 2.0: 1.35, 4.0: 1.85}
    rows = []
    for (algorithm, stage), cost in base.items():
        for payload, scale in payload_scaling.items():
            # Only the size-dependent stages scale with the payload; the RSA
            # exponentiation does not care how long the message was.
            grows = stage in ("decode_only", "full_verify") or algorithm == "HS256"
            mean = cost * (scale if grows else 1.0) * (1.0 + rng.normal(0.0, 0.01))
            rows.append([
                algorithm, stage, payload, 1_000_000,
                fmt(mean, 6), fmt(mean * 0.96, 6), fmt(mean * 1.9, 6),
            ])
    rows.sort(key=lambda r: (r[0], r[1], r[2]))
    write_csv(out_dir / "microbench.csv", header, rows)


# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(ARTIFACT_ROOT / "data" / "example"))
    parser.add_argument("--seed", type=int, default=20250906)
    args = parser.parse_args(argv)

    out_dir = Path(args.out)
    if "example" not in out_dir.resolve().name.lower():
        # The watermark guard keys on the path. Writing synthetic data somewhere
        # that does not say "example" would defeat it.
        raise SystemExit(
            f"refusing to write synthetic data to {out_dir}: the directory name must "
            "contain 'example' so the watermark and macro guards can detect it."
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    print("Generating SYNTHETIC example data (nothing here was measured):")
    make_scenarios(rng, out_dir)
    make_ramp(rng, out_dir)
    make_microbench(rng, out_dir)
    make_controller_trace(rng, out_dir)
    print(f"\nWrote synthetic example data to {out_dir}")
    print("Every file carries a 'SYNTHETIC EXAMPLE DATA' header; figures built from")
    print("it are watermarked and generated macros are wrapped in \\SYNTHVAL.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
